flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- cpphs-1.20.8
- integer-logarithms-1.0.2
- megaparsec-6.2.0
- parser-combinators-0.2.0
- primitive-0.6.2.0
- scientific-0.3.5.2
- transformers-0.5.5.0
- transformers-compat-0.5.1.4
- vector-0.12.0.1
resolver: lts-6.35
